create schema if not exists fin;

create table if not exists fin.cost_center (
    id int not null primary key generated by default as identity,
    name varchar(255) not null,
    is_active boolean not null default (true)
);


/*
    Transaction coding rules
    Transaction codes are integers.
    This will give 10 digits, the first digit would be always 1

    Second digit:
        1 - income
        2 - expence

    Third digit:
        1 - customer
        2 - employee
        3 - office rent, assets (PC, tables/chairs) etc.
        4 - services (paying or receiving money for outsourced services)

 */
create table if not exists fin.transaction_codes (
    code int not null primary key,
    name varchar(255) not null,
    description varchar default(null),
    is_active boolean not null default (true)
);

create table if not exists fin.transactions (
    id int not null primary key generated by default as identity,
    occurred_at timestamp with time zone not null,
    amount numeric(18, 2) not null,
    currency varchar(3) not null,
    cost_center_id int not null,
    code int not null
        references fin.transaction_codes(code),
    correlated_transaction_id int null
        references fin.transactions(id),
    correction_of_transaction_id int null
        references fin.transactions(id),
    description varchar(1024) null,
    external_transaction_id varchar(1024) null,
    reference_type char(10) null,
    reference_id int null,
    created_at timestamp with time zone not null default(current_timestamp),
    created_by varchar(255) not null default(-1)
);

create or replace view fin.transactions_info as
    select
        t.*,
        tc.name transaction_code_name,
        cc.name cost_center_name
    from
        fin.transactions t inner join
        fin.transaction_codes as tc on t.code = tc.code inner join
        fin.cost_center as cc on t.cost_center_id = cc.id
;

create table if not exists fin.transaction_attributes (
    id int not null primary key generated by default as identity,
    transaction_id int not null
        references fin.transactions(id),
    attribute varchar(20) not null,
    ref int not null
);
