create schema if not exists swd;
create table if not exists swd.customers (
    id int not null primary key generated by default as identity,
    name varchar(255) not null,
    country_code varchar(3) not null,
    is_active boolean not null default(true)
);
create table if not exists swd.projects (
    id int not null primary key generated by default as identity,
    name varchar(1024) not null,
    customer_id int not null references swd.customers(id),
    is_active boolean not null default(true)
);