create schema if not exists empl;
create table if not exists empl.employees (
    id int not null primary key generated by default as identity,
    name varchar(2048) not null,
    is_active boolean not null default(true)
);