create schema if not exists ref;

create table if not exists ref.exchange_rate (
    id int not null primary key generated by default as identity,
    from_curr char(3) not null,
    to_curr char(3) not null,
    -- How many from_curr need to pay to by one of to_curr
    rate numeric(18,9) not null,
    -- Date from which exchange rate is applied
    at_date date not null,
    rate_src varchar(50) null
);

create or replace view ref.exchange_rate_expanded
as
    with curr_pairs as
    (
        select
            from_curr,
            to_curr
        from ref.exchange_rate
        group by from_curr, to_curr
    ),
    curr_pairs_earlier as
    (
        select
            p.*,
            (select
            id
            from
            ref.exchange_rate r
            where
                r.from_curr = p.from_curr and
                r.to_curr = p.to_curr
            order by r.at_date, r.id
            limit 1) as id
        from
            curr_pairs p
    ),
    curr_pairs_later as
    (
        select
            p.*,
            (select
                id
            from
                ref.exchange_rate r
            where
            r.from_curr = p.from_curr and
            r.to_curr = p.to_curr
            order by r.at_date desc, r.id desc
            limit 1) as id
        from
            curr_pairs p
    )
    select
        r.id,
        r.from_curr,
        r.to_curr,
        r.rate,
        '1970-01-01' at_date,
    'EARLIER' as rate_src
    from
        curr_pairs_earlier t inner join
        ref.exchange_rate r on t.id = r.id
    union all
    select * from ref.exchange_rate
    union all
    select
        r.id,
        r.from_curr,
        r.to_curr,
        r.rate,
        '9999-12-31' at_date,
        'LATER' as rate_src
    from
        curr_pairs_later t inner join
        ref.exchange_rate r on t.id = r.id


