@secret=skdmf234i34nrkn98234444lsdklfsdf
# Docker Win
# @auth=http://auth.rd-erp.io
# @api=http://192.168.99.100/api/ref

# Docker OS X
@auth=http://auth.rd-erp.io
@api=http://localhost/api/ref


# Local
# @auth=http://localhost:4999
# @api=http://localhost:5200/api

###
# @name token
POST {{auth}}/connect/token
Content-Type: application/x-www-form-urlencoded

grant_type=password&client_id=rd&client_secret={{secret}}&username=serg&password=root&scope=rd-erp

###
POST {{api}}/currency/refresh-exchange-rates
Authorization: Bearer {{token.response.body.$.access_token}}
Content-Type: application/json


###
GET {{api}}/lists/currencies
Authorization: Bearer {{token.response.body.$.access_token}}

###
GET {{api}}/lists/cost-centers
Authorization: Bearer {{token.response.body.$.access_token}}


###
GET {{api}}/lists/transaction-codes
Authorization: Bearer {{token.response.body.$.access_token}}
